projects:
  amplifymultienvexample-prod:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: 5hhhjp6g3nftvkpkqgzqzfwrau
        maxDepth: 2
      endpoints:
        prod: >-
          https://bbmsodpbozddth6cn5vin47lgm.appsync-api.us-east-2.amazonaws.com/graphql